[package]
name = "storm_mssql"
version = "0.46.3"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/danylaporte/storm"
publish = false

[dependencies]
cache = { workspace = true, optional = true }
chrono.workspace = true
dec19x5 = { workspace = true, features = ["serde", "tiberius"], optional = true }
futures.workspace = true
metrics = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
smallvec.workspace = true
storm = { path = "../storm", features = ["mssql"] }
str_utils = { workspace = true, optional = true }
tiberius = { workspace = true, features = ["chrono", "rustls", "tds73", "winauth"] }
tokio = { workspace = true, features = ["net"] }
tokio-util.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
criterion.workspace = true
async-cell-lock = { git = "https://github.com/danylaporte/async-cell-lock.git" }
storm = { path = "../storm", features = ["derive"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[[bench]]
name = "sql_building"
harness = false

[[bench]]
name = "live_mssql"
harness = false

[features]
telemetry = ["metrics"]
